name: Beatwalker
favicon: null
layout_spectrum: 0.48255
typography_spectrum: 1
title: 'DJ/Producer '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#444444'
    - '#929292'
    - '#b9b9b9'
    - '#f0f0f0'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
