name: Beatwalker
favicon: null
layout_spectrum: 0.48255
typography_spectrum: 1
title: 'DJ/Producer '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#707382'
    - '#403732'
    - '#fefefe'
    - '#f0c884'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
